import { Context } from '@deepseek-ai/cordis'
import { describe, expect, it } from 'vitest'
import ImageGeneration, {
  ImageGenerationError,
  type ImageGenerationContext,
  type ImageGenerationProvider,
  type ImageGenerationRequest,
  type ImageGenerationResult,
} from '../src/index.ts'

const onePixel: ImageGenerationResult = {
  provider: 'arkcli',
  model: 'seedream-4-0',
  images: [{ bytes: new Uint8Array([137, 80, 78, 71]), mediaType: 'image/png', width: 1, height: 1 }],
}

const request: ImageGenerationRequest = {
  model: 'seedream-4-0',
  size: '2048x3072',
  outputFormat: 'png',
  watermark: false,
}

/** Create a provider whose resolved marker is returned in the generated bytes. */
function provider(id: string): ImageGenerationProvider {
  return {
    id,
    resolve: request => Promise.resolve({
      model: request.model ?? 'seedream-4-0',
      size: request.size,
      outputFormat: request.outputFormat,
      watermark: request.watermark,
      providerSpec: { marker: id },
    }),
    generate: input => Promise.resolve({
      provider: id,
      model: input.spec.model,
      images: [{
        ...onePixel.images[0]!,
        bytes: new TextEncoder().encode((input.spec.providerSpec as { marker: string }).marker),
      }],
    }),
  }
}

/** Mount the image generation service on a fresh context. */
async function mount(): Promise<{ ctx: Context; service: ImageGeneration }> {
  const ctx = new Context()
  await ctx.plugin(ImageGeneration)
  return { ctx, service: ctx.imageGeneration }
}

describe('ImageGeneration provider selection', () => {
  it('auto-selects the sole provider and generates from its resolved input', async () => {
    const { service } = await mount()
    service.registerProvider(provider('arkcli'))

    const spec = await service.resolve(request, {})
    const input = { prompt: 'draw a lighthouse', spec }
    const result = await service.generate(input, {})

    expect(spec).toEqual({
      provider: 'arkcli',
      model: 'seedream-4-0',
      size: '2048x3072',
      outputFormat: 'png',
      watermark: false,
      providerSpec: { marker: 'arkcli' },
    })
    expect(new TextDecoder().decode(result.images[0]!.bytes)).toBe('arkcli')
  })

  it('uses an explicitly requested provider when several are registered', async () => {
    const { service } = await mount()
    service.registerProvider(provider('first'))
    service.registerProvider(provider('arkcli'))

    const input = await service.resolve({ ...request, provider: 'arkcli' }, {})

    expect(input.provider).toBe('arkcli')
  })

  it('keeps the registry provider id when a provider returns a forged provider field', async () => {
    const { service } = await mount()
    service.registerProvider({
      id: 'arkcli',
      resolve: requested => Promise.resolve({
        provider: 'forged',
        model: requested.model ?? 'seedream-4-0',
        size: requested.size,
        outputFormat: requested.outputFormat,
        watermark: requested.watermark,
      }),
      generate: () => Promise.resolve(onePixel),
    })

    const spec = await service.resolve(request, {})

    expect(spec.provider).toBe('arkcli')
  })

  it('throws a typed missing-provider error when none is registered', async () => {
    const { service } = await mount()

    await expect(service.resolve(request, {})).rejects.toEqual(expect.objectContaining({
      name: 'ImageGenerationError',
      code: 'IMAGE_GENERATION_PROVIDER_MISSING',
    }))
  })

  it('throws a typed missing-provider error when the explicit provider is absent', async () => {
    const { service } = await mount()
    service.registerProvider(provider('first'))

    await expect(service.resolve({ ...request, provider: 'arkcli' }, {})).rejects.toEqual(
      expect.objectContaining({ code: 'IMAGE_GENERATION_PROVIDER_MISSING' }),
    )
  })

  it('throws a typed ambiguity error instead of depending on registration order', async () => {
    const { service } = await mount()
    service.registerProvider(provider('first'))
    service.registerProvider(provider('second'))

    await expect(service.resolve(request, {})).rejects.toEqual(expect.objectContaining({
      code: 'IMAGE_GENERATION_PROVIDER_AMBIGUOUS',
    }))
  })

  it('throws a typed duplicate-registration error', async () => {
    const { service } = await mount()
    service.registerProvider(provider('arkcli'))

    expect(() => service.registerProvider(provider('arkcli'))).toThrow(expect.objectContaining({
      code: 'IMAGE_GENERATION_PROVIDER_DUPLICATE',
    }))
  })

  it('rejects a blank size before provider resolution', async () => {
    const { service } = await mount()
    service.registerProvider(provider('arkcli'))

    await expect(service.resolve({ ...request, size: '   ' }, {})).rejects.toEqual(expect.objectContaining({
      code: 'IMAGE_GENERATION_INVALID_SIZE',
    }))
  })
})

describe('ImageGeneration lifecycle and execution context', () => {
  it('forwards the same abort signal through resolve and generate', async () => {
    const { service } = await mount()
    const contexts: ImageGenerationContext[] = []
    service.registerProvider({
      id: 'arkcli',
      resolve: (requested, context) => {
        contexts.push(context)
        return Promise.resolve({
          model: requested.model ?? 'seedream-4-0',
          size: requested.size,
          outputFormat: requested.outputFormat,
          watermark: requested.watermark,
        })
      },
      generate: (_input, context) => { contexts.push(context); return Promise.resolve(onePixel) },
    })
    const controller = new AbortController()
    const context = { signal: controller.signal }

    const spec = await service.resolve(request, context)
    await service.generate({ prompt: 'draw a lighthouse', spec }, context)

    expect(contexts).toEqual([context, context])
    expect(contexts.every(seen => seen.signal === controller.signal)).toBe(true)
  })

  it('removes a provider through the returned disposer', async () => {
    const { service } = await mount()
    const dispose = service.registerProvider(provider('arkcli'))
    await expect(service.resolve(request, {})).resolves.toMatchObject({ provider: 'arkcli' })

    dispose()

    await expect(service.resolve(request, {})).rejects.toBeInstanceOf(ImageGenerationError)
  })

  it('removes a provider when the contributing fiber is disposed', async () => {
    const { ctx, service } = await mount()
    const fiber = await ctx.plugin(Object.assign((inner: Context) => {
      inner.imageGeneration.registerProvider(provider('arkcli'))
    }, { inject: ['imageGeneration'] }))
    await expect(service.resolve(request, {})).resolves.toMatchObject({ provider: 'arkcli' })

    await fiber.dispose()

    await expect(service.resolve(request, {})).rejects.toEqual(expect.objectContaining({
      code: 'IMAGE_GENERATION_PROVIDER_MISSING',
    }))
  })
})
