import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, describe, expect, it } from 'vitest'
import {
  collectArchitectureCatalog,
  renderArchitectureCatalogModule,
} from './architecture-catalog.ts'

const roots: string[] = []

afterEach(() => {
  for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true })
})

function workspace(): string {
  const root = mkdtempSync(join(tmpdir(), 'dsh-architecture-catalog-'))
  roots.push(root)
  const writePackage = (group: string, leaf: string, manifest: object): void => {
    const directory = join(root, 'packages', group, leaf)
    mkdirSync(directory, { recursive: true })
    writeFileSync(join(directory, 'package.json'), `${JSON.stringify(manifest, null, 2)}\n`)
  }
  writePackage('util', 'foundation', {
    name: '@deepseek-ai/dsh-foundation',
    description: 'Small browser-safe foundation',
  })
  writePackage('client', 'tool-feature', {
    name: '@deepseek-ai/dsh-tool-feature',
    description: 'A dynamic client tool surface',
    peerDependencies: {
      '@deepseek-ai/dsh-foundation': 'workspace:^',
      react: '^18.2.0',
    },
    exports: {
      '.': './lib/index.js',
      './client': './lib/client.js',
      './remote': './lib/remote.js',
    },
    dsh: { client: { platform: 'web' } },
  })
  writePackage('bundle', 'web', {
    name: '@deepseek-ai/dsh-web-bundle',
    description: 'Web profile composition',
    dsh: { bundle: './cordis.patch.yml' },
  })
  writePackage('delivery', 'delivery', {
    name: '@changanhua/dsh-delivery',
    description: 'Personal delivery control plane',
    peerDependencies: {
      '@deepseek-ai/dsh-foundation': 'workspace:^',
      '@deepseek-ai/dsh-tool-feature': 'workspace:^',
    },
  })

  const nested = join(root, 'packages', 'client', 'tool-feature', 'tests', 'fixture')
  mkdirSync(nested, { recursive: true })
  writeFileSync(join(nested, 'package.json'), '{"name":"@deepseek-ai/dsh-test-fixture"}\n')
  return root
}

describe('collectArchitectureCatalog', () => {
  it('derives the browser catalog from formal workspace manifests only', () => {
    expect(collectArchitectureCatalog(workspace())).toEqual({
      schemaVersion: 2,
      packages: [
        {
          name: '@deepseek-ai/dsh-web-bundle',
          short: 'web-bundle',
          group: 'bundle',
          path: 'packages/bundle/web',
          description: 'Web profile composition',
          dependencies: [],
          faces: ['bundle'],
        },
        {
          name: '@deepseek-ai/dsh-tool-feature',
          short: 'tool-feature',
          group: 'client',
          path: 'packages/client/tool-feature',
          description: 'A dynamic client tool surface',
          dependencies: ['@deepseek-ai/dsh-foundation'],
          faces: ['client', 'remote', 'tool'],
        },
        {
          name: '@changanhua/dsh-delivery',
          short: 'delivery',
          group: 'delivery',
          path: 'packages/delivery/delivery',
          description: 'Personal delivery control plane',
          dependencies: ['@deepseek-ai/dsh-foundation', '@deepseek-ai/dsh-tool-feature'],
          faces: ['package'],
        },
        {
          name: '@deepseek-ai/dsh-foundation',
          short: 'foundation',
          group: 'util',
          path: 'packages/util/foundation',
          description: 'Small browser-safe foundation',
          dependencies: [],
          faces: ['package'],
        },
      ],
    })
  })

  it('renders a deterministic typed client module', () => {
    expect(renderArchitectureCatalogModule({ schemaVersion: 2, packages: [] })).toBe(
      '// Generated by scripts/gen-architecture-catalog.ts. Do not edit by hand.\n'
      + 'import type { ArchitectureCatalog } from \'./catalog.ts\'\n\n'
      + '/** Package declarations from the checkout that built this Client artifact. */\n'
      + 'export const architectureCatalog: ArchitectureCatalog = {\n'
      + '  schemaVersion: 2,\n'
      + '  packages: [\n'
      + '  ],\n'
      + '}\n',
    )
  })
})
