/** Build-time package catalog consumed by the Architecture workspace. */

import { globSync, readFileSync } from 'node:fs'
import { dirname, resolve, sep } from 'node:path'

const SCOPE = '@deepseek-ai/dsh-'

export type ArchitectureFace = 'bundle' | 'client' | 'package' | 'remote' | 'tool'

export interface ArchitecturePackage {
  readonly name: string
  readonly short: string
  readonly group: string
  readonly path: string
  readonly description: string
  readonly dependencies: readonly string[]
  readonly faces: readonly ArchitectureFace[]
}

export interface ArchitectureCatalog {
  readonly schemaVersion: 1
  readonly packages: readonly ArchitecturePackage[]
}

/** Collect the current checkout's formal `packages/<group>/<leaf>` manifests. */
export function collectArchitectureCatalog(root: string): ArchitectureCatalog {
  const packages = globSync('packages/*/*/package.json', { cwd: root })
    .map(path => path.split(sep).join('/'))
    .sort()
    .flatMap((manifestPath): ArchitecturePackage[] => {
      const manifest = JSON.parse(readFileSync(resolve(root, manifestPath), 'utf8')) as {
        name?: string
        description?: string
        peerDependencies?: Record<string, string>
        exports?: Record<string, unknown>
        dsh?: { bundle?: unknown; client?: unknown }
      }
      if (manifest.name?.startsWith(SCOPE) !== true) return []
      const [, group, leaf] = manifestPath.split('/')
      if (group === undefined || leaf === undefined) {
        throw new Error(`architecture-catalog: unexpected package path ${manifestPath}`)
      }
      if (manifest.description === undefined || manifest.description.trim() === '') {
        throw new Error(`architecture-catalog: ${manifest.name} declares no description`)
      }
      const short = manifest.name.slice(SCOPE.length)
      const faces: ArchitectureFace[] = []
      if (manifest.dsh?.client !== undefined) faces.push('client')
      if (manifest.dsh?.bundle !== undefined) faces.push('bundle')
      if (manifest.exports?.['./remote'] !== undefined || manifest.exports?.['./typert'] !== undefined) faces.push('remote')
      if (short.startsWith('tool-')) faces.push('tool')
      if (faces.length === 0) faces.push('package')
      return [{
        name: manifest.name,
        short,
        group,
        path: dirname(manifestPath).split(sep).join('/'),
        description: manifest.description,
        dependencies: Object.keys(manifest.peerDependencies ?? {})
          .filter(name => name.startsWith(SCOPE))
          .map(name => name.slice(SCOPE.length))
          .sort(),
        faces,
      }]
    })
  return { schemaVersion: 1, packages }
}

/** Render the deterministic browser module committed beside the feature. */
export function renderArchitectureCatalogModule(catalog: ArchitectureCatalog): string {
  const quote = (value: string): string => `'${value
    .replaceAll('\\', '\\\\')
    .replaceAll("'", "\\'")
    .replaceAll('\r', '\\r')
    .replaceAll('\n', '\\n')}'`
  const lines = [
    '// Generated by scripts/gen-architecture-catalog.ts. Do not edit by hand.',
    "import type { ArchitectureCatalog } from './catalog.ts'",
    '',
    '/** Package declarations from the checkout that built this Client artifact. */',
    'export const architectureCatalog: ArchitectureCatalog = {',
    '  schemaVersion: 1,',
    '  packages: [',
  ]
  for (const pkg of catalog.packages) {
    lines.push(
      '    {',
      `      name: ${quote(pkg.name)},`,
      `      short: ${quote(pkg.short)},`,
      `      group: ${quote(pkg.group)},`,
      `      path: ${quote(pkg.path)},`,
      `      description: ${quote(pkg.description)},`,
      '      dependencies: [',
      ...pkg.dependencies.map(dependency => `        ${quote(dependency)},`),
      '      ],',
      '      faces: [',
      ...pkg.faces.map(face => `        ${quote(face)},`),
      '      ],',
      '    },',
    )
  }
  lines.push('  ],', '}', '')
  return lines.join('\n')
}
