/**
 * Controlled, registry-led migration of personal packages out of the official
 * npm scope. It deliberately changes source references only: lockfiles and
 * generated catalogs are regenerated by their owning commands afterwards.
 *
 * Usage: `tsx scripts/rescope-personal-packages.ts [--check|--write]`.
 * `--check` is the default and fails while an eligible legacy reference remains.
 */

import { execFileSync } from 'node:child_process'
import { readFileSync, realpathSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(import.meta.dirname, '..')
const REGISTRY_PATH = 'downstream/package-identities.json'
const EXTENSIONS = ['.ts', '.tsx', '.js', '.mjs', '.cjs', '.json', '.yml', '.yaml', '.md', '.tpl'] as const

export interface PersonalPackageRename {
  readonly directory: string
  readonly legacyName: string
  readonly sourceName: string
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === 'object' && !Array.isArray(value)
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

/** Return whether a tracked file is a historic record or generated derivative. */
export function excludedFromPersonalRescope(file: string): boolean {
  if (file === REGISTRY_PATH || file === 'pnpm-lock.yaml'
    || file === 'scripts/rescope-personal-packages.ts'
    || file === 'scripts/rescope-personal-packages.spec.ts') return true
  if (file.startsWith('.agents/notes/') || file.startsWith('scripts/snapshots/')) return true
  if (file.startsWith('docs/specs/') || file.startsWith('docs/plans/') || file.startsWith('docs/superpowers/plans/')) return true
  if (file.endsWith('.i18n.yaml')) return true
  if (file.endsWith('.generated.ts')) return true
  if (/^docs\/(?:.*(?:catalog|module-graph|graph-atlas|persistence-catalog)).*\.(?:md|ya?ml)$/u.test(file)) return true
  return !EXTENSIONS.some(extension => file.endsWith(extension))
}

/** Decode the registry-v2 `legacyName` and `sourceName` fields. */
export function personalPackageRenamesFromRegistry(parsed: unknown): {
  repositoryUrl: string
  renames: readonly PersonalPackageRename[]
} {
  if (!isRecord(parsed)) throw new Error(`${REGISTRY_PATH} must be an object`)
  if (parsed.schemaVersion !== 2) throw new Error(`${REGISTRY_PATH}.schemaVersion must be 2`)
  if (typeof parsed.personalRepositoryUrl !== 'string' || parsed.personalRepositoryUrl === '') {
    throw new Error(`${REGISTRY_PATH}.personalRepositoryUrl must be a non-empty string`)
  }
  if (!Array.isArray(parsed.personalPackages)) throw new Error(`${REGISTRY_PATH}.personalPackages must be an array`)

  const renames = parsed.personalPackages.map((value, index) => {
    if (!isRecord(value)) throw new Error(`${REGISTRY_PATH}.personalPackages[${String(index)}] must be an object`)
    const legacyName = value.legacyName
    const sourceName = value.sourceName
    if (value.sourceIdentity !== 'personal' || typeof value.directory !== 'string'
      || typeof legacyName !== 'string' || typeof sourceName !== 'string') {
      throw new Error(`${REGISTRY_PATH}.personalPackages[${String(index)}] is not a complete personal rename`)
    }
    return { directory: value.directory, legacyName, sourceName }
  })
  return { repositoryUrl: parsed.personalRepositoryUrl, renames }
}

/** Read the registry-v2 source identities. */
export function loadPersonalPackageRenames(root: string = ROOT): {
  repositoryUrl: string
  renames: readonly PersonalPackageRename[]
} {
  return personalPackageRenamesFromRegistry(JSON.parse(readFileSync(resolve(root, REGISTRY_PATH), 'utf8')) as unknown)
}

/**
 * Rewrite only whole package-name tokens. A legacy package may have a longer
 * sibling (`dsh-delivery` / `dsh-delivery-local`), so longer names run first
 * and the right boundary excludes npm-name characters.
 */
export function rewritePersonalPackageText(text: string, renames: readonly PersonalPackageRename[]): {
  text: string
  replacements: number
} {
  let replacements = 0
  let output = text
  for (const rename of [...renames].sort((left, right) => right.legacyName.length - left.legacyName.length)) {
    const expression = new RegExp(
      `(?<![A-Za-z0-9@._/-])${escapeRegExp(rename.legacyName)}(?=$|[^A-Za-z0-9@._-])`,
      'g',
    )
    output = output.replace(expression, () => {
      replacements += 1
      return rename.sourceName
    })
  }
  return { text: output, replacements }
}

export function normalizePersonalManifest(
  text: string,
  rename: PersonalPackageRename,
  repositoryUrl: string,
  renames: readonly PersonalPackageRename[],
): string {
  const parsed: unknown = JSON.parse(rewritePersonalPackageText(text, renames).text)
  if (!isRecord(parsed)) throw new Error(`${rename.directory}/package.json must be an object`)
  const manifest: Record<string, unknown> = { ...parsed }
  manifest.name = rename.sourceName
  manifest.repository = { type: 'git', url: repositoryUrl, directory: rename.directory }
  manifest.private = true
  delete manifest.publishConfig
  return `${JSON.stringify(manifest, null, 2)}\n`
}

function trackedFiles(root: string): string[] {
  return execFileSync('git', ['ls-files', '-z'], { cwd: root, encoding: 'utf8' })
    .split('\0')
    .filter(file => file !== '' && !excludedFromPersonalRescope(file))
}

export interface PersonalRescopeResult {
  readonly files: readonly string[]
  readonly replacements: number
}

/** Check or write the source-only rescope. No caller may mutate without `--write`. */
export function rescopePersonalPackages(root: string = ROOT, write = false): PersonalRescopeResult {
  const { repositoryUrl, renames } = loadPersonalPackageRenames(root)
  const changes: string[] = []
  let replacements = 0
  const byManifestPath = new Map(renames.map(rename => [`${rename.directory}/package.json`, rename]))

  for (const file of trackedFiles(root)) {
    const path = resolve(root, file)
    const before = readFileSync(path, 'utf8')
    const manifest = byManifestPath.get(file)
    const referenceRewrite = rewritePersonalPackageText(before, renames)
    const rewritten = manifest === undefined
      ? referenceRewrite
      : {
        text: normalizePersonalManifest(before, manifest, repositoryUrl, renames),
        replacements: referenceRewrite.replacements + 1,
      }
    if (rewritten.text === before) continue
    changes.push(file)
    replacements += rewritten.replacements
    if (write) writeFileSync(path, rewritten.text)
  }
  return { files: changes, replacements }
}

function main(): void {
  const args = process.argv.slice(2)
  if (args.some(arg => arg !== '--check' && arg !== '--write') || args.filter(arg => arg === '--write').length > 1) {
    throw new Error('usage: tsx scripts/rescope-personal-packages.ts [--check|--write]')
  }
  if (args.includes('--check') && args.includes('--write')) {
    throw new Error('--check and --write are mutually exclusive')
  }
  const write = args.includes('--write')
  const result = rescopePersonalPackages(ROOT, write)
  console.log(`rescope-personal-packages: ${write ? 'wrote' : 'checked'} ${String(result.files.length)} file(s), ${String(result.replacements)} replacement(s)`)
  if (!write && result.files.length > 0) {
    for (const file of result.files) console.error(`rescope-personal-packages: residue: ${file}`)
    process.exitCode = 1
  }
}

if (process.argv[1] !== undefined && realpathSync(process.argv[1]) === realpathSync(fileURLToPath(import.meta.url))) {
  main()
}
